### ISSUE TITLE
Reexporting members does not work

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/babel-plugin-ember-modules-api-polyfill#14]
Example:

```js
export { capitalize } from '@ember/string';
```

**Comment by rwjblue** [comment]
Interesting. What would you expect it to transpile to?  What does it transpile to now?

**Comment by Turbo87** [comment]
I would expect it to transpile to 

```
export const capitalize = Ember.String.capitalize;
```

or 

```
const capitalize = Ember.String.capitalize;

export capitalize;
```

**Comment by rwjblue** [comment]
Ahh, I see now what is going on.  We are only processing `ImportDeclaration`s but we will also need to process `ExportNamedDeclaration`s (though the actual processing is a bit different).
