### ISSUE TITLE
Cannot read property 'get' of null

### ISSUE THREAD

**Issue by lifeart** [ember-cli/babel-plugin-ember-modules-api-polyfill#185]
I saw https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/issues/112 in project

after updating to "babel-plugin-ember-modules-api-polyfill": "3.4.0" CI starts failing with:

```
warning Resolution field "babel-plugin-ember-modules-api-polyfill@3.4.0" is incompatible with requested version "babel-plugin-ember-modules-api-polyfill@^2.6.0"

+ ./node_modules/.bin/ember test

Build Error (broccoli-persistent-filter:Babel > [Babel: ember-test-helpers]) in @ember/test-helpers/setup-context.js

@ember/test-helpers/setup-context.js: Cannot read property 'get' of null

```

upgrading `ember-cli-babel` to latest does not help, downgrading `babel-plugin-ember-modules-api-polyfill` to `babel-plugin-ember-modules-api-polyfill@2.13.4` solve problem.

package.json:

```
"ember-cli": "~3.22.0",
"ember-cli-babel": "7.24.0",
"ember-source": "3.24.0"
```

**Comment by rwjblue** [comment]
@lifeart hmm, it seems you are forcing the resolution here (and therefore making things that expected 2.x of this package to get 3.x). That is a fundamentally invalid thing to do 😄 (there were breaking changes, as indicated by that major version bump 😜 ).

**Comment by lifeart** [comment]
@rwjblue agree, but it seems not related to <https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/117/files>

**Comment by rwjblue** [comment]
You have a repro?

**Comment by lifeart** [comment]
Can't get it bubbling on a fresh project, closing it for now.
