### ISSUE TITLE
Breaks with @babel/preset-env@7.4.3

### ISSUE THREAD

**Issue by machty** [ember-cli/babel-plugin-ember-modules-api-polyfill#64]
I wanted to make sure this issue didn't fall in the cracks, as I believe it nuked almost an entire day of work for me yesterday, and the way it fails is veeery subtle and tricky.

See here for references to this issue:

- https://github.com/babel/ember-cli-babel/pull/284
- https://github.com/babel/ember-cli-babel/issues/281#issuecomment-501334930

In short, there are combinations of values in `config/target.js` and the plugins added in `@babel/preset-env@7.4.3` that will cause things like `import EmberObject from '@ember/object'` to be converted to an undefined `_EmberObject` instead of `Ember.Object`.

cc @chadhietala and @rwjblue

**Comment by lukemelia** [comment]
I have seen this as well. It is a tortuous experience.

**Comment by Leooo** [comment]
same here. A massively tricky one to debug. Without @rwjblue 's help we could never have.

For now we reverted to using

```
/* eslint-env node */
module.exports = {
  browsers: [
    'ie 9',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```

in our config/target.js 

from

```
/* eslint-env node */
module.exports = {
  browsers: [
    'last 1 version',
    '> 2% in GB'
  ]
};
```

but obviously not ideal so happy to follow the resolution on this.

**Comment by raido** [comment]
I recently ran into same thing and @rwjblue pointed me here. 

Reference issue I opened over here: 

https://github.com/babel/ember-cli-babel/issues/316

**Comment by raido** [comment]
@rwjblue any hope of this getting some attention?

I tried to debug to some extent it by linking this package locally, but did not manage to find where exactly transformations break.

**Comment by rwjblue** [comment]
The fix for this is basically the same as what was done in https://github.com/ember-data/babel-plugin-ember-data-packages-polyfill/pull/3

**Comment by rwjblue** [comment]
This seemed to crop up again when running Babel 7.10.0+ (released 2020-05-25). I'm looking into fixing (based on my last comment).

**Comment by runspired** [comment]
@rwjblue I have time this afternoon if needed to supply a fix

**Comment by rwjblue** [comment]
Thanks @runspired, definitely will appreciate the help (either in reviews or impl).

After a bunch of general repo cleanup, I've reproduced the failures being reported in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/108.

**Comment by rwjblue** [comment]
ember-cli-babel@7.20.1 was just released, and should fix the underlying issue.

https://github.com/babel/ember-cli-babel/releases/tag/v7.20.1
