### ISSUE TITLE
@ember/debug does not have a deprecate export

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/babel-plugin-ember-modules-api-polyfill#77]
I tracked this down to this library. I think this particular export is missing?

Error:
```
Build Error (broccoli-persistent-filter:Babel) in ember-resolver/resolvers/classic/index.js

/home/gaurav/dev/emberjs/ember-twiddle/ember-resolver/resolvers/classic/index.js: @ember/debug does not have a deprecate export
  2 | 
  3 | import Ember from 'ember';
> 4 | import { assert, deprecate, warn } from '@ember/debug';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  5 | import EmberObject, { get, computed } from '@ember/object';
  6 | import { dasherize, classify, underscore } from '@ember/string';
  7 | import { DEBUG } from '@glimmer/env';
```

Reproduction : https://github.com/Gaurav0/ember-twiddle/pull/new/update_ember_resolver

cc/ @rwjblue

**Comment by rwjblue** [comment]
Those particular exports are not handled by this library. These are normally done by babel-plugin-debug-macros, see the config that ember-cli-babel uses here;

https://github.com/babel/ember-cli-babel/blob/acfc22b62d5e48091a628e3937a197b325f51517/index.js#L457-L478
